# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.room_invitation_request import RoomInvitationRequest

class TestRoomInvitationRequest(unittest.TestCase):
    """RoomInvitationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoomInvitationRequest:
        """Test RoomInvitationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoomInvitationRequest`
        """
        model = RoomInvitationRequest()
        if include_optional:
            return RoomInvitationRequest(
                invitations = [
                    docspace.models.room_invitation.RoomInvitation(
                        email = 'Sydney_Roberts4@hotmail.com', 
                        id = 'aae1e103-bca5-9fa1-ba8c-42058b4abf28', 
                        access = 0, )
                    ],
                notify = True,
                message = 'some text',
                culture = 'some text',
                force = True
            )
        else:
            return RoomInvitationRequest(
        )
        """

    def testRoomInvitationRequest(self):
        """Test RoomInvitationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
