# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.search_area import SearchArea

class TestSearchArea(unittest.TestCase):
    """SearchArea unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchArea(self):
        """Test SearchArea"""
        # inst = SearchArea()

if __name__ == '__main__':
    unittest.main()
