# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.i_magick_geometry import IMagickGeometry

class TestIMagickGeometry(unittest.TestCase):
    """IMagickGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMagickGeometry:
        """Test IMagickGeometry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMagickGeometry`
        """
        model = IMagickGeometry()
        if include_optional:
            return IMagickGeometry(
                aspect_ratio = True,
                fill_area = True,
                greater = True,
                height = 56,
                ignore_aspect_ratio = True,
                is_percentage = True,
                less = True,
                limit_pixels = True,
                width = 56,
                x = 1234,
                y = 1234
            )
        else:
            return IMagickGeometry(
        )
        """

    def testIMagickGeometry(self):
        """Test IMagickGeometry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
