# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.link_type import LinkType

class TestLinkType(unittest.TestCase):
    """LinkType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkType(self):
        """Test LinkType"""
        # inst = LinkType()

if __name__ == '__main__':
    unittest.main()
