# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.api.files_folders_api import FilesFoldersApi


class TestFilesFoldersApi(unittest.TestCase):
    """FilesFoldersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesFoldersApi()

    def tearDown(self) -> None:
        pass

    def test_check_upload(self) -> None:
        """Test case for check_upload

        Checks upload
        """
        pass

    def test_create_folder(self) -> None:
        """Test case for create_folder

        Create a folder
        """
        pass

    def test_delete_folder(self) -> None:
        """Test case for delete_folder

        Delete a folder
        """
        pass

    def test_get_files_used_space(self) -> None:
        """Test case for get_files_used_space

        Get used space of files
        """
        pass

    def test_get_folder(self) -> None:
        """Test case for get_folder

        Get folder form filter
        """
        pass

    def test_get_folder_by_folder_id(self) -> None:
        """Test case for get_folder_by_folder_id

        Get a folder by ID
        """
        pass

    def test_get_folder_history(self) -> None:
        """Test case for get_folder_history

        Get folder history
        """
        pass

    def test_get_folder_info(self) -> None:
        """Test case for get_folder_info

        Get folder information
        """
        pass

    def test_get_folder_path(self) -> None:
        """Test case for get_folder_path

        Get the folder path
        """
        pass

    def test_get_folder_primary_external_link(self) -> None:
        """Test case for get_folder_primary_external_link

        Get primary external link
        """
        pass

    def test_get_folders(self) -> None:
        """Test case for get_folders

        Get subfolders
        """
        pass

    def test_get_my_folder(self) -> None:
        """Test case for get_my_folder

        Get the \"My documents\" section
        """
        pass

    def test_get_new_items(self) -> None:
        """Test case for get_new_items

        Get new folder items
        """
        pass

    def test_get_privacy_folder(self) -> None:
        """Test case for get_privacy_folder

        Get the \"Private Room\" section
        """
        pass

    def test_get_root_folders(self) -> None:
        """Test case for get_root_folders

        Get filtered sections
        """
        pass

    def test_get_trash_folder(self) -> None:
        """Test case for get_trash_folder

        Get the \"Trash\" section
        """
        pass

    def test_insert_file(self) -> None:
        """Test case for insert_file

        Insert a file
        """
        pass

    def test_insert_file_to_my_from_body(self) -> None:
        """Test case for insert_file_to_my_from_body

        Insert a file to the \"My documents\" section
        """
        pass

    def test_rename_folder(self) -> None:
        """Test case for rename_folder

        Rename a folder
        """
        pass

    def test_set_file_order(self) -> None:
        """Test case for set_file_order

        Sets file order in the folder with ID specified in the request
        """
        pass

    def test_upload_file(self) -> None:
        """Test case for upload_file

        Upload a file
        """
        pass

    def test_upload_file_to_my(self) -> None:
        """Test case for upload_file_to_my

        Upload a file to the \"My documents\" section
        """
        pass


if __name__ == '__main__':
    unittest.main()
