# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.quantity_request_dto import QuantityRequestDto

class TestQuantityRequestDto(unittest.TestCase):
    """QuantityRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuantityRequestDto:
        """Test QuantityRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuantityRequestDto`
        """
        model = QuantityRequestDto()
        if include_optional:
            return QuantityRequestDto(
                quantity = [{"key":"some text","value":1234}]
            )
        else:
            return QuantityRequestDto(
        )
        """

    def testQuantityRequestDto(self):
        """Test QuantityRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
