# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.api.settings_common_settings_api import SettingsCommonSettingsApi


class TestSettingsCommonSettingsApi(unittest.TestCase):
    """SettingsCommonSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsCommonSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_close_admin_helper(self) -> None:
        """Test case for close_admin_helper

        Close the admin helper
        """
        pass

    def test_complete_wizard(self) -> None:
        """Test case for complete_wizard

        Complete the Wizard settings
        """
        pass

    def test_delete_color_theme(self) -> None:
        """Test case for delete_color_theme

        Delete a color theme
        """
        pass

    def test_get_color_theme(self) -> None:
        """Test case for get_color_theme

        Get a color theme
        """
        pass

    def test_get_logo(self) -> None:
        """Test case for get_logo

        Get a portal logo
        """
        pass

    def test_get_machine_name(self) -> None:
        """Test case for get_machine_name

        Get hostname
        """
        pass

    def test_get_settings(self) -> None:
        """Test case for get_settings

        Get the portal settings
        """
        pass

    def test_get_socket_settings(self) -> None:
        """Test case for get_socket_settings

        Get the socket settings
        """
        pass

    def test_get_supported_cultures(self) -> None:
        """Test case for get_supported_cultures

        Get supported languages
        """
        pass

    def test_get_time_zones_async(self) -> None:
        """Test case for get_time_zones_async

        Get time zones
        """
        pass

    def test_gett_deep_link_settings(self) -> None:
        """Test case for gett_deep_link_settings

        Get the deep link settings
        """
        pass

    def test_payment_settings(self) -> None:
        """Test case for payment_settings

        Get the payment settings
        """
        pass

    def test_save_color_theme(self) -> None:
        """Test case for save_color_theme

        Save a color theme
        """
        pass

    def test_save_configure_deep_link(self) -> None:
        """Test case for save_configure_deep_link

        Configure the deep link settings
        """
        pass

    def test_save_dns_settings(self) -> None:
        """Test case for save_dns_settings

        Save the DNS settings
        """
        pass

    def test_save_mail_domain_settings(self) -> None:
        """Test case for save_mail_domain_settings

        Save the mail domain settings
        """
        pass

    def test_update_email_activation_settings(self) -> None:
        """Test case for update_email_activation_settings

        Update the email activation settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
