# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.security_dto import SecurityDto

class TestSecurityDto(unittest.TestCase):
    """SecurityDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecurityDto:
        """Test SecurityDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecurityDto`
        """
        model = SecurityDto()
        if include_optional:
            return SecurityDto(
                web_item_id = '{00000000-0000-0000-0000-000000000000}',
                users = [
                    docspace.models.employee_dto.EmployeeDto(
                        id = '', 
                        display_name = 'Mike Zanyatski', 
                        title = 'Manager', 
                        avatar = 'some text', 
                        avatar_original = 'some text', 
                        avatar_max = 'some text', 
                        avatar_medium = 'some text', 
                        avatar_small = 'url to small avatar', 
                        profile_url = 'some text', 
                        has_avatar = True, 
                        is_anonim = True, )
                    ],
                groups = [
                    docspace.models.group_summary_dto.GroupSummaryDto(
                        id = '', 
                        name = 'Group Name', 
                        manager = 'Jake.Zazhitski', )
                    ],
                enabled = True,
                is_sub_item = False
            )
        else:
            return SecurityDto(
        )
        """

    def testSecurityDto(self):
        """Test SecurityDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
