# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.check_conversion_request_dto_integer import CheckConversionRequestDtoInteger

class TestCheckConversionRequestDtoInteger(unittest.TestCase):
    """CheckConversionRequestDtoInteger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckConversionRequestDtoInteger:
        """Test CheckConversionRequestDtoInteger
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckConversionRequestDtoInteger`
        """
        model = CheckConversionRequestDtoInteger()
        if include_optional:
            return CheckConversionRequestDtoInteger(
                file_id = 9846,
                sync = True,
                start_convert = True,
                version = 1234,
                password = 'vfmf2vO1Kp',
                output_type = 'some text',
                create_new_if_exist = True
            )
        else:
            return CheckConversionRequestDtoInteger(
        )
        """

    def testCheckConversionRequestDtoInteger(self):
        """Test CheckConversionRequestDtoInteger"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
