# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.api.o_auth20_scope_management_api import OAuth20ScopeManagementApi


class TestOAuth20ScopeManagementApi(unittest.TestCase):
    """OAuth20ScopeManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuth20ScopeManagementApi()

    def tearDown(self) -> None:
        pass

    def test_get_scopes(self) -> None:
        """Test case for get_scopes

        Get available OAuth2 scopes
        """
        pass


if __name__ == '__main__':
    unittest.main()
