# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.subject_filter import SubjectFilter

class TestSubjectFilter(unittest.TestCase):
    """SubjectFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubjectFilter(self):
        """Test SubjectFilter"""
        # inst = SubjectFilter()

if __name__ == '__main__':
    unittest.main()
