# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.additional_white_label_settings_dto import AdditionalWhiteLabelSettingsDto

class TestAdditionalWhiteLabelSettingsDto(unittest.TestCase):
    """AdditionalWhiteLabelSettingsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdditionalWhiteLabelSettingsDto:
        """Test AdditionalWhiteLabelSettingsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdditionalWhiteLabelSettingsDto`
        """
        model = AdditionalWhiteLabelSettingsDto()
        if include_optional:
            return AdditionalWhiteLabelSettingsDto(
                start_docs_enabled = True,
                help_center_enabled = True,
                feedback_and_support_enabled = True,
                user_forum_enabled = True,
                video_guides_enabled = True,
                license_agreements_enabled = True,
                is_default = True
            )
        else:
            return AdditionalWhiteLabelSettingsDto(
        )
        """

    def testAdditionalWhiteLabelSettingsDto(self):
        """Test AdditionalWhiteLabelSettingsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
