# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.api.capabilities_api import CapabilitiesApi


class TestCapabilitiesApi(unittest.TestCase):
    """CapabilitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CapabilitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_portal_capabilities(self) -> None:
        """Test case for get_portal_capabilities

        Get portal capabilities
        """
        pass


if __name__ == '__main__':
    unittest.main()
