# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.create_api_key_request_dto import CreateApiKeyRequestDto

class TestCreateApiKeyRequestDto(unittest.TestCase):
    """CreateApiKeyRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApiKeyRequestDto:
        """Test CreateApiKeyRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApiKeyRequestDto`
        """
        model = CreateApiKeyRequestDto()
        if include_optional:
            return CreateApiKeyRequestDto(
                name = 'Winfield Upton',
                permissions = ["some text"],
                expires_in_days = 1234
            )
        else:
            return CreateApiKeyRequestDto(
                name = 'Winfield Upton',
        )
        """

    def testCreateApiKeyRequestDto(self):
        """Test CreateApiKeyRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
