# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.custom_color_themes_settings_color_item import CustomColorThemesSettingsColorItem

class TestCustomColorThemesSettingsColorItem(unittest.TestCase):
    """CustomColorThemesSettingsColorItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomColorThemesSettingsColorItem:
        """Test CustomColorThemesSettingsColorItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomColorThemesSettingsColorItem`
        """
        model = CustomColorThemesSettingsColorItem()
        if include_optional:
            return CustomColorThemesSettingsColorItem(
                accent = '#4781D1',
                buttons = '#5299E0'
            )
        else:
            return CustomColorThemesSettingsColorItem(
        )
        """

    def testCustomColorThemesSettingsColorItem(self):
        """Test CustomColorThemesSettingsColorItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
