# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.company_white_label_settings_array_wrapper import CompanyWhiteLabelSettingsArrayWrapper

class TestCompanyWhiteLabelSettingsArrayWrapper(unittest.TestCase):
    """CompanyWhiteLabelSettingsArrayWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompanyWhiteLabelSettingsArrayWrapper:
        """Test CompanyWhiteLabelSettingsArrayWrapper
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompanyWhiteLabelSettingsArrayWrapper`
        """
        model = CompanyWhiteLabelSettingsArrayWrapper()
        if include_optional:
            return CompanyWhiteLabelSettingsArrayWrapper(
                response = [
                    docspace.models.company_white_label_settings.CompanyWhiteLabelSettings(
                        company_name = 'some text', 
                        site = 'some text', 
                        email = 'Sydney_Roberts4@hotmail.com', 
                        address = 'some text', 
                        phone = 'some text', 
                        is_licensor = True, )
                    ],
                count = 56,
                links = [
                    docspace.models.active_connections_wrapper_links_inner.ActiveConnectionsWrapper_links_inner(
                        href = '', 
                        action = '', )
                    ],
                status = 56,
                status_code = 56
            )
        else:
            return CompanyWhiteLabelSettingsArrayWrapper(
        )
        """

    def testCompanyWhiteLabelSettingsArrayWrapper(self):
        """Test CompanyWhiteLabelSettingsArrayWrapper"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
