# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.payment_settings_wrapper import PaymentSettingsWrapper

class TestPaymentSettingsWrapper(unittest.TestCase):
    """PaymentSettingsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentSettingsWrapper:
        """Test PaymentSettingsWrapper
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentSettingsWrapper`
        """
        model = PaymentSettingsWrapper()
        if include_optional:
            return PaymentSettingsWrapper(
                response = docspace.models.payment_settings_dto.PaymentSettingsDto(
                    sales_email = 'some text', 
                    feedback_and_support_url = 'some text', 
                    buy_url = 'some text', 
                    standalone = True, 
                    current_license = docspace.models.current_license_info.CurrentLicenseInfo(
                        trial = True, 
                        due_date = '2008-04-10T06:30+04:00', ), 
                    max = 1234, ),
                count = 56,
                links = [
                    docspace.models.active_connections_wrapper_links_inner.ActiveConnectionsWrapper_links_inner(
                        href = '', 
                        action = '', )
                    ],
                status = 56,
                status_code = 56
            )
        else:
            return PaymentSettingsWrapper(
        )
        """

    def testPaymentSettingsWrapper(self):
        """Test PaymentSettingsWrapper"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
