# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.watermark_on_draw import WatermarkOnDraw

class TestWatermarkOnDraw(unittest.TestCase):
    """WatermarkOnDraw unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WatermarkOnDraw:
        """Test WatermarkOnDraw
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WatermarkOnDraw`
        """
        model = WatermarkOnDraw()
        if include_optional:
            return WatermarkOnDraw(
                width = -8.5,
                height = -8.5,
                margins = [1234],
                fill = 'some text',
                rotate = 1234,
                transparent = -8.5,
                paragraphs = [
                    docspace.models.paragraph.Paragraph(
                        align = 1234, 
                        runs = [
                            docspace.models.run.Run(
                                fill = [1234], 
                                text = 'some text', 
                                font_size = 'some text', )
                            ], )
                    ]
            )
        else:
            return WatermarkOnDraw(
        )
        """

    def testWatermarkOnDraw(self):
        """Test WatermarkOnDraw"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
