# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.api.settings_encryption_api import SettingsEncryptionApi


class TestSettingsEncryptionApi(unittest.TestCase):
    """SettingsEncryptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsEncryptionApi()

    def tearDown(self) -> None:
        pass

    def test_get_storage_encryption_progress(self) -> None:
        """Test case for get_storage_encryption_progress

        Get the storage encryption progress
        """
        pass

    def test_start_storage_encryption(self) -> None:
        """Test case for start_storage_encryption

        Start the storage encryption process
        """
        pass


if __name__ == '__main__':
    unittest.main()
