# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.item_key_value_pair_object_object import ItemKeyValuePairObjectObject

class TestItemKeyValuePairObjectObject(unittest.TestCase):
    """ItemKeyValuePairObjectObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemKeyValuePairObjectObject:
        """Test ItemKeyValuePairObjectObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemKeyValuePairObjectObject`
        """
        model = ItemKeyValuePairObjectObject()
        if include_optional:
            return ItemKeyValuePairObjectObject(
                key = {"int":1234,"string":"some text","boolean":true},
                value = {"int":1234,"string":"some text","boolean":true}
            )
        else:
            return ItemKeyValuePairObjectObject(
        )
        """

    def testItemKeyValuePairObjectObject(self):
        """Test ItemKeyValuePairObjectObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
