# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.dark_theme_settings_wrapper import DarkThemeSettingsWrapper

class TestDarkThemeSettingsWrapper(unittest.TestCase):
    """DarkThemeSettingsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DarkThemeSettingsWrapper:
        """Test DarkThemeSettingsWrapper
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DarkThemeSettingsWrapper`
        """
        model = DarkThemeSettingsWrapper()
        if include_optional:
            return DarkThemeSettingsWrapper(
                response = docspace.models.dark_theme_settings.DarkThemeSettings(
                    theme = 0, 
                    last_modified = '2008-04-10T06:30+04:00', ),
                count = 56,
                links = [
                    docspace.models.active_connections_wrapper_links_inner.ActiveConnectionsWrapper_links_inner(
                        href = '', 
                        action = '', )
                    ],
                status = 56,
                status_code = 56
            )
        else:
            return DarkThemeSettingsWrapper(
        )
        """

    def testDarkThemeSettingsWrapper(self):
        """Test DarkThemeSettingsWrapper"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
