# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.form_role_wrapper import FormRoleWrapper

class TestFormRoleWrapper(unittest.TestCase):
    """FormRoleWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormRoleWrapper:
        """Test FormRoleWrapper
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormRoleWrapper`
        """
        model = FormRoleWrapper()
        if include_optional:
            return FormRoleWrapper(
                response = docspace.models.form_role.FormRole(
                    room_id = 9846, 
                    role_name = 'some text', 
                    role_color = 'some text', 
                    user_id = 'aae1e103-bca5-9fa1-ba8c-42058b4abf28', 
                    sequence = 1234, 
                    submitted = True, 
                    opened_at = '2008-04-10T06:30+04:00', 
                    submission_date = '2008-04-10T06:30+04:00', ),
                count = 56,
                links = [
                    docspace.models.active_connections_wrapper_links_inner.ActiveConnectionsWrapper_links_inner(
                        href = '', 
                        action = '', )
                    ],
                status = 56,
                status_code = 56
            )
        else:
            return FormRoleWrapper(
        )
        """

    def testFormRoleWrapper(self):
        """Test FormRoleWrapper"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
