# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.api.settings_tfa_settings_api import SettingsTFASettingsApi


class TestSettingsTFASettingsApi(unittest.TestCase):
    """SettingsTFASettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsTFASettingsApi()

    def tearDown(self) -> None:
        pass

    def test_get_tfa_settings(self) -> None:
        """Test case for get_tfa_settings

        Get the TFA settings
        """
        pass

    def test_tfa_app_generate_setup_code(self) -> None:
        """Test case for tfa_app_generate_setup_code

        Generate setup code
        """
        pass

    def test_tfa_app_get_codes(self) -> None:
        """Test case for tfa_app_get_codes

        Get the TFA codes
        """
        pass

    def test_tfa_app_new_app(self) -> None:
        """Test case for tfa_app_new_app

        Unlink the TFA application
        """
        pass

    def test_tfa_app_request_new_codes(self) -> None:
        """Test case for tfa_app_request_new_codes

        Update the TFA codes
        """
        pass

    def test_tfa_confirm_url(self) -> None:
        """Test case for tfa_confirm_url

        Get confirmation email
        """
        pass

    def test_tfa_settings(self) -> None:
        """Test case for tfa_settings

        Update the TFA settings
        """
        pass

    def test_tfa_settings_link(self) -> None:
        """Test case for tfa_settings_link

        Get confirmation email for updating TFA settings
        """
        pass

    def test_tfa_validate_auth_code(self) -> None:
        """Test case for tfa_validate_auth_code

        Validate the TFA code
        """
        pass


if __name__ == '__main__':
    unittest.main()
