# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.tenant_dev_tools_access_settings import TenantDevToolsAccessSettings

class TestTenantDevToolsAccessSettings(unittest.TestCase):
    """TenantDevToolsAccessSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantDevToolsAccessSettings:
        """Test TenantDevToolsAccessSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantDevToolsAccessSettings`
        """
        model = TenantDevToolsAccessSettings()
        if include_optional:
            return TenantDevToolsAccessSettings(
                limited_access_for_users = True,
                last_modified = '2008-04-10T06:30+04:00'
            )
        else:
            return TenantDevToolsAccessSettings(
        )
        """

    def testTenantDevToolsAccessSettings(self):
        """Test TenantDevToolsAccessSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
