# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.third_party_backup_request_dto import ThirdPartyBackupRequestDto

class TestThirdPartyBackupRequestDto(unittest.TestCase):
    """ThirdPartyBackupRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThirdPartyBackupRequestDto:
        """Test ThirdPartyBackupRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThirdPartyBackupRequestDto`
        """
        model = ThirdPartyBackupRequestDto()
        if include_optional:
            return ThirdPartyBackupRequestDto(
                url = 'some text',
                login = 'some text',
                password = 'vfmf2vO1Kp',
                token = 'some text',
                customer_title = 'some text',
                provider_key = 'some text'
            )
        else:
            return ThirdPartyBackupRequestDto(
        )
        """

    def testThirdPartyBackupRequestDto(self):
        """Test ThirdPartyBackupRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
