# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.tenant_quota_settings_wrapper import TenantQuotaSettingsWrapper

class TestTenantQuotaSettingsWrapper(unittest.TestCase):
    """TenantQuotaSettingsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantQuotaSettingsWrapper:
        """Test TenantQuotaSettingsWrapper
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantQuotaSettingsWrapper`
        """
        model = TenantQuotaSettingsWrapper()
        if include_optional:
            return TenantQuotaSettingsWrapper(
                response = docspace.models.tenant_quota_settings.TenantQuotaSettings(
                    enable_quota = True, 
                    quota = 1234, 
                    last_recalculate_date = '2008-04-10T06:30+04:00', ),
                count = 56,
                links = [
                    docspace.models.active_connections_wrapper_links_inner.ActiveConnectionsWrapper_links_inner(
                        href = '', 
                        action = '', )
                    ],
                status = 56,
                status_code = 56
            )
        else:
            return TenantQuotaSettingsWrapper(
        )
        """

    def testTenantQuotaSettingsWrapper(self):
        """Test TenantQuotaSettingsWrapper"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
