# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspace.models.active_connections_item_dto import ActiveConnectionsItemDto

class TestActiveConnectionsItemDto(unittest.TestCase):
    """ActiveConnectionsItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveConnectionsItemDto:
        """Test ActiveConnectionsItemDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveConnectionsItemDto`
        """
        model = ActiveConnectionsItemDto()
        if include_optional:
            return ActiveConnectionsItemDto(
                id = 9846,
                tenant_id = 1234,
                user_id = 'aae1e103-bca5-9fa1-ba8c-42058b4abf28',
                mobile = True,
                ip = 'some text',
                country = 'some text',
                city = 'some text',
                browser = 'some text',
                platform = 'some text',
                var_date = docspace.models.api_date_time.ApiDateTime(
                    utc_time = '2008-04-10T06:30+04:00', 
                    time_zone_offset = '00:00:00', ),
                page = 'some text'
            )
        else:
            return ActiveConnectionsItemDto(
        )
        """

    def testActiveConnectionsItemDto(self):
        """Test ActiveConnectionsItemDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
