#
# (c) Copyright Ascensio System SIA 2025
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#



# import models into model package
from docspace-api-sdk.models.account_info_array_wrapper import AccountInfoArrayWrapper
from docspace-api-sdk.models.account_info_dto import AccountInfoDto
from docspace-api-sdk.models.account_login_type import AccountLoginType
from docspace-api-sdk.models.ace_short_wrapper import AceShortWrapper
from docspace-api-sdk.models.ace_short_wrapper_array_wrapper import AceShortWrapperArrayWrapper
from docspace-api-sdk.models.action_config import ActionConfig
from docspace-api-sdk.models.action_link_config import ActionLinkConfig
from docspace-api-sdk.models.action_type import ActionType
from docspace-api-sdk.models.active_connections_dto import ActiveConnectionsDto
from docspace-api-sdk.models.active_connections_item_dto import ActiveConnectionsItemDto
from docspace-api-sdk.models.active_connections_wrapper import ActiveConnectionsWrapper
from docspace-api-sdk.models.active_connections_wrapper_links_inner import ActiveConnectionsWrapperLinksInner
from docspace-api-sdk.models.additional_white_label_settings import AdditionalWhiteLabelSettings
from docspace-api-sdk.models.additional_white_label_settings_dto import AdditionalWhiteLabelSettingsDto
from docspace-api-sdk.models.additional_white_label_settings_wrapper import AdditionalWhiteLabelSettingsWrapper
from docspace-api-sdk.models.admin_message_base_settings_requests_dto import AdminMessageBaseSettingsRequestsDto
from docspace-api-sdk.models.admin_message_settings_requests_dto import AdminMessageSettingsRequestsDto
from docspace-api-sdk.models.anonymous_config_dto import AnonymousConfigDto
from docspace-api-sdk.models.api_date_time import ApiDateTime
from docspace-api-sdk.models.api_key_response_array_wrapper import ApiKeyResponseArrayWrapper
from docspace-api-sdk.models.api_key_response_dto import ApiKeyResponseDto
from docspace-api-sdk.models.api_key_response_wrapper import ApiKeyResponseWrapper
from docspace-api-sdk.models.apply_filter_option import ApplyFilterOption
from docspace-api-sdk.models.archive_room_request import ArchiveRoomRequest
from docspace-api-sdk.models.area import Area
from docspace-api-sdk.models.array_array_wrapper import ArrayArrayWrapper
from docspace-api-sdk.models.audit_event_array_wrapper import AuditEventArrayWrapper
from docspace-api-sdk.models.audit_event_dto import AuditEventDto
from docspace-api-sdk.models.auth_data import AuthData
from docspace-api-sdk.models.auth_key import AuthKey
from docspace-api-sdk.models.auth_requests_dto import AuthRequestsDto
from docspace-api-sdk.models.auth_service_requests_array_wrapper import AuthServiceRequestsArrayWrapper
from docspace-api-sdk.models.auth_service_requests_dto import AuthServiceRequestsDto
from docspace-api-sdk.models.authentication_token_dto import AuthenticationTokenDto
from docspace-api-sdk.models.authentication_token_wrapper import AuthenticationTokenWrapper
from docspace-api-sdk.models.auto_clean_up_data import AutoCleanUpData
from docspace-api-sdk.models.auto_clean_up_data_wrapper import AutoCleanUpDataWrapper
from docspace-api-sdk.models.auto_cleanup_request_dto import AutoCleanupRequestDto
from docspace-api-sdk.models.backup_dto import BackupDto
from docspace-api-sdk.models.backup_history_record import BackupHistoryRecord
from docspace-api-sdk.models.backup_history_record_array_wrapper import BackupHistoryRecordArrayWrapper
from docspace-api-sdk.models.backup_period import BackupPeriod
from docspace-api-sdk.models.backup_progress import BackupProgress
from docspace-api-sdk.models.backup_progress_enum import BackupProgressEnum
from docspace-api-sdk.models.backup_progress_wrapper import BackupProgressWrapper
from docspace-api-sdk.models.backup_restore_dto import BackupRestoreDto
from docspace-api-sdk.models.backup_schedule_dto import BackupScheduleDto
from docspace-api-sdk.models.backup_storage_type import BackupStorageType
from docspace-api-sdk.models.balance import Balance
from docspace-api-sdk.models.balance_wrapper import BalanceWrapper
from docspace-api-sdk.models.base_batch_request_dto import BaseBatchRequestDto
from docspace-api-sdk.models.base_batch_request_dto_folder_ids_inner import BaseBatchRequestDtoFolderIdsInner
from docspace-api-sdk.models.batch_request_dto import BatchRequestDto
from docspace-api-sdk.models.batch_request_dto_dest_folder_id import BatchRequestDtoDestFolderId
from docspace-api-sdk.models.batch_tags_request_dto import BatchTagsRequestDto
from docspace-api-sdk.models.boolean_wrapper import BooleanWrapper
from docspace-api-sdk.models.capabilities_dto import CapabilitiesDto
from docspace-api-sdk.models.capabilities_wrapper import CapabilitiesWrapper
from docspace-api-sdk.models.cdn_storage_settings import CdnStorageSettings
from docspace-api-sdk.models.cdn_storage_settings_wrapper import CdnStorageSettingsWrapper
from docspace-api-sdk.models.change_client_activation_request import ChangeClientActivationRequest
from docspace-api-sdk.models.change_history import ChangeHistory
from docspace-api-sdk.models.change_owner_request_dto import ChangeOwnerRequestDto
from docspace-api-sdk.models.check_conversion_request_dto_integer import CheckConversionRequestDtoInteger
from docspace-api-sdk.models.check_dest_folder_dto import CheckDestFolderDto
from docspace-api-sdk.models.check_dest_folder_result import CheckDestFolderResult
from docspace-api-sdk.models.check_dest_folder_wrapper import CheckDestFolderWrapper
from docspace-api-sdk.models.check_doc_service_url_request_dto import CheckDocServiceUrlRequestDto
from docspace-api-sdk.models.check_fill_form_draft import CheckFillFormDraft
from docspace-api-sdk.models.check_upload_request import CheckUploadRequest
from docspace-api-sdk.models.client_info_response import ClientInfoResponse
from docspace-api-sdk.models.client_response import ClientResponse
from docspace-api-sdk.models.client_secret_response import ClientSecretResponse
from docspace-api-sdk.models.co_editing_config import CoEditingConfig
from docspace-api-sdk.models.co_editing_config_mode import CoEditingConfigMode
from docspace-api-sdk.models.company_white_label_settings import CompanyWhiteLabelSettings
from docspace-api-sdk.models.company_white_label_settings_array_wrapper import CompanyWhiteLabelSettingsArrayWrapper
from docspace-api-sdk.models.company_white_label_settings_dto import CompanyWhiteLabelSettingsDto
from docspace-api-sdk.models.company_white_label_settings_wrapper import CompanyWhiteLabelSettingsWrapper
from docspace-api-sdk.models.configuration_dto_integer import ConfigurationDtoInteger
from docspace-api-sdk.models.configuration_integer_wrapper import ConfigurationIntegerWrapper
from docspace-api-sdk.models.confirm_data import ConfirmData
from docspace-api-sdk.models.confirm_dto import ConfirmDto
from docspace-api-sdk.models.confirm_type import ConfirmType
from docspace-api-sdk.models.confirm_wrapper import ConfirmWrapper
from docspace-api-sdk.models.contact import Contact
from docspace-api-sdk.models.content_disposition import ContentDisposition
from docspace-api-sdk.models.content_type import ContentType
from docspace-api-sdk.models.conversation_result_array_wrapper import ConversationResultArrayWrapper
from docspace-api-sdk.models.conversation_result_dto import ConversationResultDto
from docspace-api-sdk.models.cookie_settings_dto import CookieSettingsDto
from docspace-api-sdk.models.cookie_settings_requests_dto import CookieSettingsRequestsDto
from docspace-api-sdk.models.cookie_settings_wrapper import CookieSettingsWrapper
from docspace-api-sdk.models.copy_as_json_element import CopyAsJsonElement
from docspace-api-sdk.models.copy_as_json_element_dest_folder_id import CopyAsJsonElementDestFolderId
from docspace-api-sdk.models.cover_request_dto import CoverRequestDto
from docspace-api-sdk.models.covers_result_array_wrapper import CoversResultArrayWrapper
from docspace-api-sdk.models.covers_result_dto import CoversResultDto
from docspace-api-sdk.models.create_api_key_request_dto import CreateApiKeyRequestDto
from docspace-api-sdk.models.create_client_request import CreateClientRequest
from docspace-api-sdk.models.create_file_json_element import CreateFileJsonElement
from docspace-api-sdk.models.create_file_json_element_template_id import CreateFileJsonElementTemplateId
from docspace-api-sdk.models.create_folder import CreateFolder
from docspace-api-sdk.models.create_room_from_template_dto import CreateRoomFromTemplateDto
from docspace-api-sdk.models.create_room_request_dto import CreateRoomRequestDto
from docspace-api-sdk.models.create_tag_request_dto import CreateTagRequestDto
from docspace-api-sdk.models.create_text_or_html_file import CreateTextOrHtmlFile
from docspace-api-sdk.models.create_third_party_room import CreateThirdPartyRoom
from docspace-api-sdk.models.create_webhooks_config_requests_dto import CreateWebhooksConfigRequestsDto
from docspace-api-sdk.models.cron import Cron
from docspace-api-sdk.models.cron_params import CronParams
from docspace-api-sdk.models.csp_dto import CspDto
from docspace-api-sdk.models.csp_requests_dto import CspRequestsDto
from docspace-api-sdk.models.csp_wrapper import CspWrapper
from docspace-api-sdk.models.culture import Culture
from docspace-api-sdk.models.culture_specific_external_resource import CultureSpecificExternalResource
from docspace-api-sdk.models.culture_specific_external_resources import CultureSpecificExternalResources
from docspace-api-sdk.models.currencies_array_wrapper import CurrenciesArrayWrapper
from docspace-api-sdk.models.currencies_dto import CurrenciesDto
from docspace-api-sdk.models.current_license_info import CurrentLicenseInfo
from docspace-api-sdk.models.custom_color_themes_settings_color_item import CustomColorThemesSettingsColorItem
from docspace-api-sdk.models.custom_color_themes_settings_dto import CustomColorThemesSettingsDto
from docspace-api-sdk.models.custom_color_themes_settings_item import CustomColorThemesSettingsItem
from docspace-api-sdk.models.custom_color_themes_settings_requests_dto import CustomColorThemesSettingsRequestsDto
from docspace-api-sdk.models.custom_color_themes_settings_wrapper import CustomColorThemesSettingsWrapper
from docspace-api-sdk.models.custom_filter_parameters import CustomFilterParameters
from docspace-api-sdk.models.custom_navigation_item import CustomNavigationItem
from docspace-api-sdk.models.custom_navigation_item_array_wrapper import CustomNavigationItemArrayWrapper
from docspace-api-sdk.models.custom_navigation_item_wrapper import CustomNavigationItemWrapper
from docspace-api-sdk.models.customer_config_dto import CustomerConfigDto
from docspace-api-sdk.models.customer_info_dto import CustomerInfoDto
from docspace-api-sdk.models.customer_info_wrapper import CustomerInfoWrapper
from docspace-api-sdk.models.customer_operations_report_request_dto import CustomerOperationsReportRequestDto
from docspace-api-sdk.models.customization_config_dto import CustomizationConfigDto
from docspace-api-sdk.models.dark_theme_settings import DarkThemeSettings
from docspace-api-sdk.models.dark_theme_settings_request_dto import DarkThemeSettingsRequestDto
from docspace-api-sdk.models.dark_theme_settings_type import DarkThemeSettingsType
from docspace-api-sdk.models.dark_theme_settings_wrapper import DarkThemeSettingsWrapper
from docspace-api-sdk.models.date_to_auto_clean_up import DateToAutoCleanUp
from docspace-api-sdk.models.db_tenant import DbTenant
from docspace-api-sdk.models.db_tenant_partner import DbTenantPartner
from docspace-api-sdk.models.deep_link_configuration_requests_dto import DeepLinkConfigurationRequestsDto
from docspace-api-sdk.models.deep_link_dto import DeepLinkDto
from docspace-api-sdk.models.deep_link_handling_mode import DeepLinkHandlingMode
from docspace-api-sdk.models.delete import Delete
from docspace-api-sdk.models.delete_batch_request_dto import DeleteBatchRequestDto
from docspace-api-sdk.models.delete_folder import DeleteFolder
from docspace-api-sdk.models.delete_room_request import DeleteRoomRequest
from docspace-api-sdk.models.delete_version_batch_request_dto import DeleteVersionBatchRequestDto
from docspace-api-sdk.models.display_request_dto import DisplayRequestDto
from docspace-api-sdk.models.distributed_task_status import DistributedTaskStatus
from docspace-api-sdk.models.dns_settings_requests_dto import DnsSettingsRequestsDto
from docspace-api-sdk.models.doc_service_url_dto import DocServiceUrlDto
from docspace-api-sdk.models.doc_service_url_wrapper import DocServiceUrlWrapper
from docspace-api-sdk.models.document_builder_task_dto import DocumentBuilderTaskDto
from docspace-api-sdk.models.document_builder_task_wrapper import DocumentBuilderTaskWrapper
from docspace-api-sdk.models.document_config_dto import DocumentConfigDto
from docspace-api-sdk.models.double_wrapper import DoubleWrapper
from docspace-api-sdk.models.download_request_dto import DownloadRequestDto
from docspace-api-sdk.models.download_request_item_dto import DownloadRequestItemDto
from docspace-api-sdk.models.download_request_item_dto_key import DownloadRequestItemDtoKey
from docspace-api-sdk.models.draft_location_integer import DraftLocationInteger
from docspace-api-sdk.models.duplicate_request_dto import DuplicateRequestDto
from docspace-api-sdk.models.edit_history_array_wrapper import EditHistoryArrayWrapper
from docspace-api-sdk.models.edit_history_author import EditHistoryAuthor
from docspace-api-sdk.models.edit_history_changes_wrapper import EditHistoryChangesWrapper
from docspace-api-sdk.models.edit_history_data_dto import EditHistoryDataDto
from docspace-api-sdk.models.edit_history_data_wrapper import EditHistoryDataWrapper
from docspace-api-sdk.models.edit_history_dto import EditHistoryDto
from docspace-api-sdk.models.edit_history_url import EditHistoryUrl
from docspace-api-sdk.models.editor_configuration_dto import EditorConfigurationDto
from docspace-api-sdk.models.editor_type import EditorType
from docspace-api-sdk.models.email_activation_settings import EmailActivationSettings
from docspace-api-sdk.models.email_activation_settings_wrapper import EmailActivationSettingsWrapper
from docspace-api-sdk.models.email_member_request_dto import EmailMemberRequestDto
from docspace-api-sdk.models.email_validation_key_model import EmailValidationKeyModel
from docspace-api-sdk.models.embedded_config import EmbeddedConfig
from docspace-api-sdk.models.employee_activation_status import EmployeeActivationStatus
from docspace-api-sdk.models.employee_array_wrapper import EmployeeArrayWrapper
from docspace-api-sdk.models.employee_dto import EmployeeDto
from docspace-api-sdk.models.employee_full_array_wrapper import EmployeeFullArrayWrapper
from docspace-api-sdk.models.employee_full_dto import EmployeeFullDto
from docspace-api-sdk.models.employee_full_wrapper import EmployeeFullWrapper
from docspace-api-sdk.models.employee_status import EmployeeStatus
from docspace-api-sdk.models.employee_type import EmployeeType
from docspace-api-sdk.models.encryprtion_status import EncryprtionStatus
from docspace-api-sdk.models.encryption_keys_config import EncryptionKeysConfig
from docspace-api-sdk.models.encryption_settings import EncryptionSettings
from docspace-api-sdk.models.encryption_settings_wrapper import EncryptionSettingsWrapper
from docspace-api-sdk.models.entry_type import EntryType
from docspace-api-sdk.models.error_response import ErrorResponse
from docspace-api-sdk.models.exchange_token200_response import ExchangeToken200Response
from docspace-api-sdk.models.external_share_dto import ExternalShareDto
from docspace-api-sdk.models.external_share_request_param import ExternalShareRequestParam
from docspace-api-sdk.models.external_share_wrapper import ExternalShareWrapper
from docspace-api-sdk.models.feature_used_dto import FeatureUsedDto
from docspace-api-sdk.models.feedback_config import FeedbackConfig
from docspace-api-sdk.models.file_conflict_resolve_type import FileConflictResolveType
from docspace-api-sdk.models.file_dto_integer import FileDtoInteger
from docspace-api-sdk.models.file_dto_integer_security import FileDtoIntegerSecurity
from docspace-api-sdk.models.file_dto_integer_view_accessibility import FileDtoIntegerViewAccessibility
from docspace-api-sdk.models.file_entry_array_wrapper import FileEntryArrayWrapper
from docspace-api-sdk.models.file_entry_dto import FileEntryDto
from docspace-api-sdk.models.file_entry_type import FileEntryType
from docspace-api-sdk.models.file_entry_wrapper import FileEntryWrapper
from docspace-api-sdk.models.file_integer_array_wrapper import FileIntegerArrayWrapper
from docspace-api-sdk.models.file_integer_wrapper import FileIntegerWrapper
from docspace-api-sdk.models.file_link import FileLink
from docspace-api-sdk.models.file_link_request import FileLinkRequest
from docspace-api-sdk.models.file_link_wrapper import FileLinkWrapper
from docspace-api-sdk.models.file_operation_array_wrapper import FileOperationArrayWrapper
from docspace-api-sdk.models.file_operation_dto import FileOperationDto
from docspace-api-sdk.models.file_operation_type import FileOperationType
from docspace-api-sdk.models.file_operation_wrapper import FileOperationWrapper
from docspace-api-sdk.models.file_reference import FileReference
from docspace-api-sdk.models.file_reference_data import FileReferenceData
from docspace-api-sdk.models.file_reference_wrapper import FileReferenceWrapper
from docspace-api-sdk.models.file_share import FileShare
from docspace-api-sdk.models.file_share_array_wrapper import FileShareArrayWrapper
from docspace-api-sdk.models.file_share_dto import FileShareDto
from docspace-api-sdk.models.file_share_params import FileShareParams
from docspace-api-sdk.models.file_share_wrapper import FileShareWrapper
from docspace-api-sdk.models.file_status import FileStatus
from docspace-api-sdk.models.file_type import FileType
from docspace-api-sdk.models.file_upload_result_dto import FileUploadResultDto
from docspace-api-sdk.models.file_upload_result_wrapper import FileUploadResultWrapper
from docspace-api-sdk.models.files_settings_dto import FilesSettingsDto
from docspace-api-sdk.models.files_settings_dto_internal_formats import FilesSettingsDtoInternalFormats
from docspace-api-sdk.models.files_settings_wrapper import FilesSettingsWrapper
from docspace-api-sdk.models.files_statistics_folder import FilesStatisticsFolder
from docspace-api-sdk.models.files_statistics_result_dto import FilesStatisticsResultDto
from docspace-api-sdk.models.files_statistics_result_wrapper import FilesStatisticsResultWrapper
from docspace-api-sdk.models.filling_form_result_dto_integer import FillingFormResultDtoInteger
from docspace-api-sdk.models.filling_form_result_integer_wrapper import FillingFormResultIntegerWrapper
from docspace-api-sdk.models.filter_type import FilterType
from docspace-api-sdk.models.finish_dto import FinishDto
from docspace-api-sdk.models.fire_base_user import FireBaseUser
from docspace-api-sdk.models.fire_base_user_wrapper import FireBaseUserWrapper
from docspace-api-sdk.models.firebase_dto import FirebaseDto
from docspace-api-sdk.models.firebase_requests_dto import FirebaseRequestsDto
from docspace-api-sdk.models.folder_content_dto_integer import FolderContentDtoInteger
from docspace-api-sdk.models.folder_content_integer_array_wrapper import FolderContentIntegerArrayWrapper
from docspace-api-sdk.models.folder_content_integer_wrapper import FolderContentIntegerWrapper
from docspace-api-sdk.models.folder_dto_integer import FolderDtoInteger
from docspace-api-sdk.models.folder_dto_string import FolderDtoString
from docspace-api-sdk.models.folder_integer_array_wrapper import FolderIntegerArrayWrapper
from docspace-api-sdk.models.folder_integer_wrapper import FolderIntegerWrapper
from docspace-api-sdk.models.folder_string_array_wrapper import FolderStringArrayWrapper
from docspace-api-sdk.models.folder_string_wrapper import FolderStringWrapper
from docspace-api-sdk.models.folder_type import FolderType
from docspace-api-sdk.models.form_filling_manage_action import FormFillingManageAction
from docspace-api-sdk.models.form_filling_status import FormFillingStatus
from docspace-api-sdk.models.form_gallery_dto import FormGalleryDto
from docspace-api-sdk.models.form_role import FormRole
from docspace-api-sdk.models.form_role_array_wrapper import FormRoleArrayWrapper
from docspace-api-sdk.models.form_role_wrapper import FormRoleWrapper
from docspace-api-sdk.models.forms_item_array_wrapper import FormsItemArrayWrapper
from docspace-api-sdk.models.forms_item_dto import FormsItemDto
from docspace-api-sdk.models.get_reference_data_dto_integer import GetReferenceDataDtoInteger
from docspace-api-sdk.models.goback_config import GobackConfig
from docspace-api-sdk.models.greeting_settings_requests_dto import GreetingSettingsRequestsDto
from docspace-api-sdk.models.group_array_wrapper import GroupArrayWrapper
from docspace-api-sdk.models.group_dto import GroupDto
from docspace-api-sdk.models.group_request_dto import GroupRequestDto
from docspace-api-sdk.models.group_summary_array_wrapper import GroupSummaryArrayWrapper
from docspace-api-sdk.models.group_summary_dto import GroupSummaryDto
from docspace-api-sdk.models.group_wrapper import GroupWrapper
from docspace-api-sdk.models.hide_confirm_convert_request_dto import HideConfirmConvertRequestDto
from docspace-api-sdk.models.history_action import HistoryAction
from docspace-api-sdk.models.history_array_wrapper import HistoryArrayWrapper
from docspace-api-sdk.models.history_data import HistoryData
from docspace-api-sdk.models.history_dto import HistoryDto
from docspace-api-sdk.models.i_compress_wrapper import ICompressWrapper
from docspace-api-sdk.models.i_magick_geometry import IMagickGeometry
from docspace-api-sdk.models.ip_restriction import IPRestriction
from docspace-api-sdk.models.ip_restriction_array_wrapper import IPRestrictionArrayWrapper
from docspace-api-sdk.models.ip_restrictions_settings import IPRestrictionsSettings
from docspace-api-sdk.models.ip_restrictions_settings_wrapper import IPRestrictionsSettingsWrapper
from docspace-api-sdk.models.info_config_dto import InfoConfigDto
from docspace-api-sdk.models.int64_wrapper import Int64Wrapper
from docspace-api-sdk.models.invite_users_request_dto import InviteUsersRequestDto
from docspace-api-sdk.models.ip_restriction_base import IpRestrictionBase
from docspace-api-sdk.models.ip_restrictions_dto import IpRestrictionsDto
from docspace-api-sdk.models.ip_restrictions_wrapper import IpRestrictionsWrapper
from docspace-api-sdk.models.is_default_white_label_logos_array_wrapper import IsDefaultWhiteLabelLogosArrayWrapper
from docspace-api-sdk.models.is_default_white_label_logos_dto import IsDefaultWhiteLabelLogosDto
from docspace-api-sdk.models.is_default_white_label_logos_wrapper import IsDefaultWhiteLabelLogosWrapper
from docspace-api-sdk.models.item_key_value_pair_object_object import ItemKeyValuePairObjectObject
from docspace-api-sdk.models.item_key_value_pair_string_boolean import ItemKeyValuePairStringBoolean
from docspace-api-sdk.models.item_key_value_pair_string_logo_requests_dto import ItemKeyValuePairStringLogoRequestsDto
from docspace-api-sdk.models.item_key_value_pair_string_string import ItemKeyValuePairStringString
from docspace-api-sdk.models.key_value_pair_boolean_string import KeyValuePairBooleanString
from docspace-api-sdk.models.key_value_pair_boolean_string_wrapper import KeyValuePairBooleanStringWrapper
from docspace-api-sdk.models.key_value_pair_string_string_values import KeyValuePairStringStringValues
from docspace-api-sdk.models.link_account_request_dto import LinkAccountRequestDto
from docspace-api-sdk.models.link_type import LinkType
from docspace-api-sdk.models.lock_file_parameters import LockFileParameters
from docspace-api-sdk.models.login_event_array_wrapper import LoginEventArrayWrapper
from docspace-api-sdk.models.login_event_dto import LoginEventDto
from docspace-api-sdk.models.login_provider import LoginProvider
from docspace-api-sdk.models.login_settings_dto import LoginSettingsDto
from docspace-api-sdk.models.login_settings_request_dto import LoginSettingsRequestDto
from docspace-api-sdk.models.login_settings_wrapper import LoginSettingsWrapper
from docspace-api-sdk.models.logo import Logo
from docspace-api-sdk.models.logo_config_dto import LogoConfigDto
from docspace-api-sdk.models.logo_cover import LogoCover
from docspace-api-sdk.models.logo_request import LogoRequest
from docspace-api-sdk.models.logo_requests_dto import LogoRequestsDto
from docspace-api-sdk.models.mail_domain_settings_requests_dto import MailDomainSettingsRequestsDto
from docspace-api-sdk.models.manage_form_filling_dto_integer import ManageFormFillingDtoInteger
from docspace-api-sdk.models.member_base_request_dto import MemberBaseRequestDto
from docspace-api-sdk.models.member_request_dto import MemberRequestDto
from docspace-api-sdk.models.members_request import MembersRequest
from docspace-api-sdk.models.mention_message_wrapper import MentionMessageWrapper
from docspace-api-sdk.models.mention_wrapper import MentionWrapper
from docspace-api-sdk.models.mention_wrapper_array_wrapper import MentionWrapperArrayWrapper
from docspace-api-sdk.models.message_action import MessageAction
from docspace-api-sdk.models.migrating_api_files import MigratingApiFiles
from docspace-api-sdk.models.migrating_api_group import MigratingApiGroup
from docspace-api-sdk.models.migrating_api_user import MigratingApiUser
from docspace-api-sdk.models.migration_api_info import MigrationApiInfo
from docspace-api-sdk.models.migration_status_dto import MigrationStatusDto
from docspace-api-sdk.models.migration_status_wrapper import MigrationStatusWrapper
from docspace-api-sdk.models.mobile_phone_activation_status import MobilePhoneActivationStatus
from docspace-api-sdk.models.mobile_requests_dto import MobileRequestsDto
from docspace-api-sdk.models.module import Module
from docspace-api-sdk.models.module_type import ModuleType
from docspace-api-sdk.models.module_wrapper import ModuleWrapper
from docspace-api-sdk.models.new_items_dto_file_entry_dto import NewItemsDtoFileEntryDto
from docspace-api-sdk.models.new_items_dto_room_new_items_dto import NewItemsDtoRoomNewItemsDto
from docspace-api-sdk.models.new_items_file_entry_array_wrapper import NewItemsFileEntryArrayWrapper
from docspace-api-sdk.models.new_items_room_new_items_array_wrapper import NewItemsRoomNewItemsArrayWrapper
from docspace-api-sdk.models.no_content_result import NoContentResult
from docspace-api-sdk.models.no_content_result_wrapper import NoContentResultWrapper
from docspace-api-sdk.models.notification_settings_dto import NotificationSettingsDto
from docspace-api-sdk.models.notification_settings_requests_dto import NotificationSettingsRequestsDto
from docspace-api-sdk.models.notification_settings_wrapper import NotificationSettingsWrapper
from docspace-api-sdk.models.notification_type import NotificationType
from docspace-api-sdk.models.o_auth20_token import OAuth20Token
from docspace-api-sdk.models.object_array_wrapper import ObjectArrayWrapper
from docspace-api-sdk.models.object_wrapper import ObjectWrapper
from docspace-api-sdk.models.operation_dto import OperationDto
from docspace-api-sdk.models.options import Options
from docspace-api-sdk.models.order_by import OrderBy
from docspace-api-sdk.models.order_request_dto import OrderRequestDto
from docspace-api-sdk.models.orders_item_request_dto_integer import OrdersItemRequestDtoInteger
from docspace-api-sdk.models.orders_request_dto_integer import OrdersRequestDtoInteger
from docspace-api-sdk.models.owner_change_instructions_dto import OwnerChangeInstructionsDto
from docspace-api-sdk.models.owner_change_instructions_wrapper import OwnerChangeInstructionsWrapper
from docspace-api-sdk.models.owner_id_settings_request_dto import OwnerIdSettingsRequestDto
from docspace-api-sdk.models.pageable_modification_response import PageableModificationResponse
from docspace-api-sdk.models.pageable_response import PageableResponse
from docspace-api-sdk.models.pageable_response_client_info_response import PageableResponseClientInfoResponse
from docspace-api-sdk.models.paragraph import Paragraph
from docspace-api-sdk.models.password_hasher import PasswordHasher
from docspace-api-sdk.models.password_settings_dto import PasswordSettingsDto
from docspace-api-sdk.models.password_settings_requests_dto import PasswordSettingsRequestsDto
from docspace-api-sdk.models.password_settings_wrapper import PasswordSettingsWrapper
from docspace-api-sdk.models.payment_calculation import PaymentCalculation
from docspace-api-sdk.models.payment_calculation_wrapper import PaymentCalculationWrapper
from docspace-api-sdk.models.payment_method_status import PaymentMethodStatus
from docspace-api-sdk.models.payment_settings_dto import PaymentSettingsDto
from docspace-api-sdk.models.payment_settings_wrapper import PaymentSettingsWrapper
from docspace-api-sdk.models.payment_url_requests_dto import PaymentUrlRequestsDto
from docspace-api-sdk.models.payments import Payments
from docspace-api-sdk.models.permissions_config import PermissionsConfig
from docspace-api-sdk.models.plugins_config import PluginsConfig
from docspace-api-sdk.models.plugins_dto import PluginsDto
from docspace-api-sdk.models.price_dto import PriceDto
from docspace-api-sdk.models.product_administrator_dto import ProductAdministratorDto
from docspace-api-sdk.models.product_administrator_wrapper import ProductAdministratorWrapper
from docspace-api-sdk.models.product_quantity_type import ProductQuantityType
from docspace-api-sdk.models.product_type import ProductType
from docspace-api-sdk.models.provider_array_wrapper import ProviderArrayWrapper
from docspace-api-sdk.models.provider_dto import ProviderDto
from docspace-api-sdk.models.provider_filter import ProviderFilter
from docspace-api-sdk.models.quantity_request_dto import QuantityRequestDto
from docspace-api-sdk.models.quota import Quota
from docspace-api-sdk.models.quota_array_wrapper import QuotaArrayWrapper
from docspace-api-sdk.models.quota_dto import QuotaDto
from docspace-api-sdk.models.quota_filter import QuotaFilter
from docspace-api-sdk.models.quota_settings_requests_dto import QuotaSettingsRequestsDto
from docspace-api-sdk.models.quota_settings_requests_dto_default_quota import QuotaSettingsRequestsDtoDefaultQuota
from docspace-api-sdk.models.quota_state import QuotaState
from docspace-api-sdk.models.quota_wrapper import QuotaWrapper
from docspace-api-sdk.models.recaptcha_type import RecaptchaType
from docspace-api-sdk.models.recent_config import RecentConfig
from docspace-api-sdk.models.report_dto import ReportDto
from docspace-api-sdk.models.report_wrapper import ReportWrapper
from docspace-api-sdk.models.review_config import ReviewConfig
from docspace-api-sdk.models.room_data_lifetime_dto import RoomDataLifetimeDto
from docspace-api-sdk.models.room_data_lifetime_period import RoomDataLifetimePeriod
from docspace-api-sdk.models.room_from_template_status_dto import RoomFromTemplateStatusDto
from docspace-api-sdk.models.room_from_template_status_wrapper import RoomFromTemplateStatusWrapper
from docspace-api-sdk.models.room_invitation import RoomInvitation
from docspace-api-sdk.models.room_invitation_request import RoomInvitationRequest
from docspace-api-sdk.models.room_link_request import RoomLinkRequest
from docspace-api-sdk.models.room_new_items_dto import RoomNewItemsDto
from docspace-api-sdk.models.room_security_dto import RoomSecurityDto
from docspace-api-sdk.models.room_security_error import RoomSecurityError
from docspace-api-sdk.models.room_security_wrapper import RoomSecurityWrapper
from docspace-api-sdk.models.room_template_dto import RoomTemplateDto
from docspace-api-sdk.models.room_template_status_dto import RoomTemplateStatusDto
from docspace-api-sdk.models.room_template_status_wrapper import RoomTemplateStatusWrapper
from docspace-api-sdk.models.room_type import RoomType
from docspace-api-sdk.models.rooms_notification_settings_dto import RoomsNotificationSettingsDto
from docspace-api-sdk.models.rooms_notification_settings_wrapper import RoomsNotificationSettingsWrapper
from docspace-api-sdk.models.rooms_notifications_settings_request_dto import RoomsNotificationsSettingsRequestDto
from docspace-api-sdk.models.run import Run
from docspace-api-sdk.models.string_array_wrapper import STRINGArrayWrapper
from docspace-api-sdk.models.sales_requests_dto import SalesRequestsDto
from docspace-api-sdk.models.save_as_pdf_integer import SaveAsPdfInteger
from docspace-api-sdk.models.save_form_role_mapping_dto_integer import SaveFormRoleMappingDtoInteger
from docspace-api-sdk.models.schedule import Schedule
from docspace-api-sdk.models.schedule_wrapper import ScheduleWrapper
from docspace-api-sdk.models.scope_response import ScopeResponse
from docspace-api-sdk.models.search_area import SearchArea
from docspace-api-sdk.models.security_array_wrapper import SecurityArrayWrapper
from docspace-api-sdk.models.security_dto import SecurityDto
from docspace-api-sdk.models.security_requests_dto import SecurityRequestsDto
from docspace-api-sdk.models.session_request import SessionRequest
from docspace-api-sdk.models.set_manager_request import SetManagerRequest
from docspace-api-sdk.models.set_public_dto import SetPublicDto
from docspace-api-sdk.models.settings_dto import SettingsDto
from docspace-api-sdk.models.settings_request_dto import SettingsRequestDto
from docspace-api-sdk.models.settings_wrapper import SettingsWrapper
from docspace-api-sdk.models.setup_code import SetupCode
from docspace-api-sdk.models.setup_code_wrapper import SetupCodeWrapper
from docspace-api-sdk.models.sex_enum import SexEnum
from docspace-api-sdk.models.share_filter_type import ShareFilterType
from docspace-api-sdk.models.signup_account_request_dto import SignupAccountRequestDto
from docspace-api-sdk.models.smtp_operation_status_requests_dto import SmtpOperationStatusRequestsDto
from docspace-api-sdk.models.smtp_operation_status_requests_wrapper import SmtpOperationStatusRequestsWrapper
from docspace-api-sdk.models.smtp_settings_dto import SmtpSettingsDto
from docspace-api-sdk.models.smtp_settings_wrapper import SmtpSettingsWrapper
from docspace-api-sdk.models.sort_order import SortOrder
from docspace-api-sdk.models.sorted_by_type import SortedByType
from docspace-api-sdk.models.sso_certificate import SsoCertificate
from docspace-api-sdk.models.sso_field_mapping import SsoFieldMapping
from docspace-api-sdk.models.sso_idp_certificate_advanced import SsoIdpCertificateAdvanced
from docspace-api-sdk.models.sso_idp_settings import SsoIdpSettings
from docspace-api-sdk.models.sso_settings_requests_dto import SsoSettingsRequestsDto
from docspace-api-sdk.models.sso_settings_v2 import SsoSettingsV2
from docspace-api-sdk.models.sso_settings_v2_wrapper import SsoSettingsV2Wrapper
from docspace-api-sdk.models.sso_sp_certificate_advanced import SsoSpCertificateAdvanced
from docspace-api-sdk.models.start_edit import StartEdit
from docspace-api-sdk.models.start_filling_form import StartFillingForm
from docspace-api-sdk.models.start_filling_mode import StartFillingMode
from docspace-api-sdk.models.start_reassign_request_dto import StartReassignRequestDto
from docspace-api-sdk.models.start_update_user_type_dto import StartUpdateUserTypeDto
from docspace-api-sdk.models.status import Status
from docspace-api-sdk.models.storage_array_wrapper import StorageArrayWrapper
from docspace-api-sdk.models.storage_dto import StorageDto
from docspace-api-sdk.models.storage_encryption_requests_dto import StorageEncryptionRequestsDto
from docspace-api-sdk.models.storage_filter import StorageFilter
from docspace-api-sdk.models.storage_requests_dto import StorageRequestsDto
from docspace-api-sdk.models.storage_settings import StorageSettings
from docspace-api-sdk.models.storage_settings_wrapper import StorageSettingsWrapper
from docspace-api-sdk.models.string_wrapper import StringWrapper
from docspace-api-sdk.models.sub_account import SubAccount
from docspace-api-sdk.models.subject_filter import SubjectFilter
from docspace-api-sdk.models.subject_type import SubjectType
from docspace-api-sdk.models.submit_form import SubmitForm
from docspace-api-sdk.models.tariff import Tariff
from docspace-api-sdk.models.tariff_state import TariffState
from docspace-api-sdk.models.tariff_wrapper import TariffWrapper
from docspace-api-sdk.models.task_progress_response_dto import TaskProgressResponseDto
from docspace-api-sdk.models.task_progress_response_wrapper import TaskProgressResponseWrapper
from docspace-api-sdk.models.templates_config import TemplatesConfig
from docspace-api-sdk.models.templates_request_dto import TemplatesRequestDto
from docspace-api-sdk.models.tenant_audit_settings import TenantAuditSettings
from docspace-api-sdk.models.tenant_audit_settings_wrapper import TenantAuditSettingsWrapper
from docspace-api-sdk.models.tenant_banner_settings import TenantBannerSettings
from docspace-api-sdk.models.tenant_banner_settings_dto import TenantBannerSettingsDto
from docspace-api-sdk.models.tenant_banner_settings_wrapper import TenantBannerSettingsWrapper
from docspace-api-sdk.models.tenant_deep_link_settings import TenantDeepLinkSettings
from docspace-api-sdk.models.tenant_deep_link_settings_wrapper import TenantDeepLinkSettingsWrapper
from docspace-api-sdk.models.tenant_dev_tools_access_settings import TenantDevToolsAccessSettings
from docspace-api-sdk.models.tenant_dev_tools_access_settings_dto import TenantDevToolsAccessSettingsDto
from docspace-api-sdk.models.tenant_dev_tools_access_settings_wrapper import TenantDevToolsAccessSettingsWrapper
from docspace-api-sdk.models.tenant_domain_validator import TenantDomainValidator
from docspace-api-sdk.models.tenant_dto import TenantDto
from docspace-api-sdk.models.tenant_entity_quota_settings import TenantEntityQuotaSettings
from docspace-api-sdk.models.tenant_industry import TenantIndustry
from docspace-api-sdk.models.tenant_quota import TenantQuota
from docspace-api-sdk.models.tenant_quota_feature_dto import TenantQuotaFeatureDto
from docspace-api-sdk.models.tenant_quota_settings import TenantQuotaSettings
from docspace-api-sdk.models.tenant_quota_settings_requests_dto import TenantQuotaSettingsRequestsDto
from docspace-api-sdk.models.tenant_quota_settings_wrapper import TenantQuotaSettingsWrapper
from docspace-api-sdk.models.tenant_quota_wrapper import TenantQuotaWrapper
from docspace-api-sdk.models.tenant_room_quota_settings import TenantRoomQuotaSettings
from docspace-api-sdk.models.tenant_room_quota_settings_wrapper import TenantRoomQuotaSettingsWrapper
from docspace-api-sdk.models.tenant_status import TenantStatus
from docspace-api-sdk.models.tenant_trusted_domains_type import TenantTrustedDomainsType
from docspace-api-sdk.models.tenant_user_invitation_settings_dto import TenantUserInvitationSettingsDto
from docspace-api-sdk.models.tenant_user_invitation_settings_request_dto import TenantUserInvitationSettingsRequestDto
from docspace-api-sdk.models.tenant_user_invitation_settings_wrapper import TenantUserInvitationSettingsWrapper
from docspace-api-sdk.models.tenant_user_quota_settings import TenantUserQuotaSettings
from docspace-api-sdk.models.tenant_user_quota_settings_wrapper import TenantUserQuotaSettingsWrapper
from docspace-api-sdk.models.tenant_wallet_settings import TenantWalletSettings
from docspace-api-sdk.models.tenant_wallet_settings_wrapper import TenantWalletSettingsWrapper
from docspace-api-sdk.models.tenant_wrapper import TenantWrapper
from docspace-api-sdk.models.terminate_request_dto import TerminateRequestDto
from docspace-api-sdk.models.tfa_requests_dto import TfaRequestsDto
from docspace-api-sdk.models.tfa_requests_dto_type import TfaRequestsDtoType
from docspace-api-sdk.models.tfa_settings_array_wrapper import TfaSettingsArrayWrapper
from docspace-api-sdk.models.tfa_settings_dto import TfaSettingsDto
from docspace-api-sdk.models.tfa_validate_requests_dto import TfaValidateRequestsDto
from docspace-api-sdk.models.third_party_backup_request_dto import ThirdPartyBackupRequestDto
from docspace-api-sdk.models.third_party_params import ThirdPartyParams
from docspace-api-sdk.models.third_party_params_array_wrapper import ThirdPartyParamsArrayWrapper
from docspace-api-sdk.models.third_party_request_dto import ThirdPartyRequestDto
from docspace-api-sdk.models.thumbnail import Thumbnail
from docspace-api-sdk.models.thumbnails_data_dto import ThumbnailsDataDto
from docspace-api-sdk.models.thumbnails_data_wrapper import ThumbnailsDataWrapper
from docspace-api-sdk.models.thumbnails_request import ThumbnailsRequest
from docspace-api-sdk.models.timezones_requests_array_wrapper import TimezonesRequestsArrayWrapper
from docspace-api-sdk.models.timezones_requests_dto import TimezonesRequestsDto
from docspace-api-sdk.models.top_up_deposit_request_dto import TopUpDepositRequestDto
from docspace-api-sdk.models.turn_on_admin_message_settings_request_dto import TurnOnAdminMessageSettingsRequestDto
from docspace-api-sdk.models.unknown_wrapper import UnknownWrapper
from docspace-api-sdk.models.update_api_key_request import UpdateApiKeyRequest
from docspace-api-sdk.models.update_client_request import UpdateClientRequest
from docspace-api-sdk.models.update_comment import UpdateComment
from docspace-api-sdk.models.update_file import UpdateFile
from docspace-api-sdk.models.update_group_request import UpdateGroupRequest
from docspace-api-sdk.models.update_member_request_dto import UpdateMemberRequestDto
from docspace-api-sdk.models.update_members_quota_request_dto import UpdateMembersQuotaRequestDto
from docspace-api-sdk.models.update_members_quota_request_dto_quota import UpdateMembersQuotaRequestDtoQuota
from docspace-api-sdk.models.update_members_request_dto import UpdateMembersRequestDto
from docspace-api-sdk.models.update_photo_member_request import UpdatePhotoMemberRequest
from docspace-api-sdk.models.update_room_request import UpdateRoomRequest
from docspace-api-sdk.models.update_rooms_quota_request_dto_integer import UpdateRoomsQuotaRequestDtoInteger
from docspace-api-sdk.models.update_rooms_room_ids_request_dto_integer import UpdateRoomsRoomIdsRequestDtoInteger
from docspace-api-sdk.models.update_webhooks_config_requests_dto import UpdateWebhooksConfigRequestsDto
from docspace-api-sdk.models.upload_request_dto import UploadRequestDto
from docspace-api-sdk.models.upload_result_dto import UploadResultDto
from docspace-api-sdk.models.upload_result_wrapper import UploadResultWrapper
from docspace-api-sdk.models.usage_space_stat_item_array_wrapper import UsageSpaceStatItemArrayWrapper
from docspace-api-sdk.models.usage_space_stat_item_dto import UsageSpaceStatItemDto
from docspace-api-sdk.models.user_config import UserConfig
from docspace-api-sdk.models.user_info import UserInfo
from docspace-api-sdk.models.user_info_wrapper import UserInfoWrapper
from docspace-api-sdk.models.user_invitation import UserInvitation
from docspace-api-sdk.models.user_invitation_request_dto import UserInvitationRequestDto
from docspace-api-sdk.models.validation_result import ValidationResult
from docspace-api-sdk.models.wallet_quantity_request_dto import WalletQuantityRequestDto
from docspace-api-sdk.models.watermark_additions import WatermarkAdditions
from docspace-api-sdk.models.watermark_dto import WatermarkDto
from docspace-api-sdk.models.watermark_on_draw import WatermarkOnDraw
from docspace-api-sdk.models.watermark_request_dto import WatermarkRequestDto
from docspace-api-sdk.models.web_item_security_requests_dto import WebItemSecurityRequestsDto
from docspace-api-sdk.models.web_items_security_requests_dto import WebItemsSecurityRequestsDto
from docspace-api-sdk.models.web_plugin_array_wrapper import WebPluginArrayWrapper
from docspace-api-sdk.models.web_plugin_dto import WebPluginDto
from docspace-api-sdk.models.web_plugin_requests import WebPluginRequests
from docspace-api-sdk.models.web_plugin_wrapper import WebPluginWrapper
from docspace-api-sdk.models.webhook_group_status import WebhookGroupStatus
from docspace-api-sdk.models.webhook_retry_requests_dto import WebhookRetryRequestsDto
from docspace-api-sdk.models.webhook_trigger import WebhookTrigger
from docspace-api-sdk.models.webhooks_config_dto import WebhooksConfigDto
from docspace-api-sdk.models.webhooks_config_with_status_array_wrapper import WebhooksConfigWithStatusArrayWrapper
from docspace-api-sdk.models.webhooks_config_with_status_dto import WebhooksConfigWithStatusDto
from docspace-api-sdk.models.webhooks_config_wrapper import WebhooksConfigWrapper
from docspace-api-sdk.models.webhooks_log_array_wrapper import WebhooksLogArrayWrapper
from docspace-api-sdk.models.webhooks_log_dto import WebhooksLogDto
from docspace-api-sdk.models.webhooks_log_wrapper import WebhooksLogWrapper
from docspace-api-sdk.models.white_label_item_array_wrapper import WhiteLabelItemArrayWrapper
from docspace-api-sdk.models.white_label_item_dto import WhiteLabelItemDto
from docspace-api-sdk.models.white_label_item_path_dto import WhiteLabelItemPathDto
from docspace-api-sdk.models.white_label_requests_dto import WhiteLabelRequestsDto
from docspace-api-sdk.models.wizard_requests_dto import WizardRequestsDto
from docspace-api-sdk.models.wizard_settings import WizardSettings
from docspace-api-sdk.models.wizard_settings_wrapper import WizardSettingsWrapper
