# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DateToAutoCleanUp(int, Enum):
    """
    [1 - One week, 2 - Two weeks, 3 - One month, 4 - Thirty days, 5 - Two months, 6 - Three months]
    """

    """
    allowed enum values
    """
    OneWeek = 1
    TwoWeeks = 2
    OneMonth = 3
    ThirtyDays = 4
    TwoMonths = 5
    ThreeMonths = 6

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DateToAutoCleanUp from a JSON string"""
        return cls(json.loads(json_str))


