# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FileStatus(int, Enum):
    """
    [0 - None, 1 - Is editing, 2 - Is new, 4 - Is converting, 8 - Is original, 16 - Is editing alone, 32 - Is favorite, 64 - Is template, 128 - Is fill form draft, 256 - Is completed form]
    """

    """
    allowed enum values
    """
    None = 0
    IsEditing = 1
    IsNew = 2
    IsConverting = 4
    IsOriginal = 8
    IsEditingAlone = 16
    IsFavorite = 32
    IsTemplate = 64
    IsFillFormDraft = 128
    IsCompletedForm = 256

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FileStatus from a JSON string"""
        return cls(json.loads(json_str))


