# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FolderType(int, Enum):
    """
    [0 - Default, 1 - Coomon, 2 - Bunch, 3 - Trash, 5 - User, 6 - Share, 8 - Projects, 10 - Favourites, 11 - Recent, 12 - Templates, 13 - Privacy, 14 - Virtual rooms, 15 - Filling forms room, 16 - Editing room, 19 - Custom room, 20 - Archive, 21 - Thirdparty backup, 22 - Public room, 25 - Ready form folder, 26 - In process form folder, 27 - Form filling folder done, 28 - Form filling folder in progress, 29 - Virtual Data Room, 30 - Room templates folder, 31 - AI room]
    """

    """
    allowed enum values
    """
    DEFAULT = 0
    COMMON = 1
    BUNCH = 2
    TRASH = 3
    USER = 5
    SHARE = 6
    Projects = 8
    Favorites = 10
    Recent = 11
    Templates = 12
    Privacy = 13
    VirtualRooms = 14
    FillingFormsRoom = 15
    EditingRoom = 16
    CustomRoom = 19
    Archive = 20
    ThirdpartyBackup = 21
    PublicRoom = 22
    ReadyFormFolder = 25
    InProcessFormFolder = 26
    FormFillingFolderDone = 27
    FormFillingFolderInProgress = 28
    VirtualDataRoom = 29
    RoomTemplates = 30
    AiRoom = 31

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FolderType from a JSON string"""
        return cls(json.loads(json_str))


