# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Payments(int, Enum):
    """
    [0 - Paid, 1 - Free]
    """

    """
    allowed enum values
    """
    Paid = 0
    Free = 1

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Payments from a JSON string"""
        return cls(json.loads(json_str))


