# coding: utf-8

"""
    ASC.Web.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProductType(int, Enum):
    """
    [0 - None, 2 - Documents, 3 - Login, 4 - Others, 5 - People, 7 - Settings]
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_4 = 4
    NUMBER_5 = 5
    NUMBER_7 = 7

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProductType from a JSON string"""
        return cls(json.loads(json_str))


