# coding: utf-8

"""
    Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TenantIndustry(int, Enum):
    """
    [0 - Other, 1 - Accounting, 2 - Advertising marketing PR, 3 - Banking, 4 - Consulting, 5 - Design, 6 - Education, 7 - Environment, 8 - Financial services, 9 - Health care, 10 - IT, 11 - Legal, 12 - Manufacturing, 13 - Public sector, 14 - Publishing, 15 - Retail sales, 16 - Telecommunications]
    """

    """
    allowed enum values
    """
    Other = 0
    Accounting = 1
    AdvertisingMarketingPR = 2
    Banking = 3
    Consulting = 4
    Design = 5
    Education = 6
    Environment = 7
    FinancialServices = 8
    HealthCare = 9
    IT = 10
    Legal = 11
    Manufacturing = 12
    PublicSector = 13
    Publishing = 14
    RetailSales = 15
    Telecommunications = 16

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TenantIndustry from a JSON string"""
        return cls(json.loads(json_str))


